version: 0.0
os: linux
files:
  #S3버킷에서 복사할 파일의 위치
  - source:  /
    #zip파일을 복사해 압출을 풀 위치
    destination: /home/ubuntu/app

permissions:
  - object: /
    pattern: "*"
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
      BeforeInstall: script/before_install.sh
      AfterInstall: 
        - location: script/after_install.sh
          timeout: 600
          runas: ubuntu