version: 0.0
os: linux
files:
  #S3버킷에서 복사할 파일의 위치
  - source:  /
    #zip파일을 복사해 압출을 풀 위치
    destination: /home/ubuntu/app

hooks:
      AfterInstall: 
        - location: script/deploy.sh
          timeout: 600
          runas: ubuntu