version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9

jobs:
    build-and-push:
      docker:
        # specify the version you desire here
        - image: circleci/node:12.13.1
  
        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
      working_directory: ~/repo
  
      steps:
        - checkout
  
        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
  
  
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run: npm install
        
workflows:
  deploy_application:
    jobs:
      - build-and-push
      - aws-code-deploy/deploy:
          #aws code-deploy설정
          application-name: api-codedeploy-agent
          deployment-group: api-codedeploy-agent-group

          service-role-arn: arn:aws:iam::901562421220:role/aws-code-deploy-role

          #배포파일(.zip) upload/download위치 (S3위치)
          bundle-bucket: node-api-bucket          
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
          #build-and-push작업이 완료되어야 배포진행
          requires:
            - build-and-push
          #master branch가 push되었을때만 배포
          filters:
              branches:
                only: master
        