version: 2.1
orbs:
  aws-code-deploy-sample: circleci/aws-code-deploy@0.0.9

jobs:
    build-and-push:
      docker:
        # specify the version you desire here
        - image: circleci/node:12.13.1
  
        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
  
      working_directory: ~/repo
  
      steps:
        - checkout
  
        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
  
        - run: npm install
        
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
  
        - run: npm test
        
workflows:
  deploy_application:
    jobs:
      - build-and-push
      - aws-code-deploy-sample/deploy:
          application-name: node-code-deploy
          deployment-group: node-code-deploy-group
          service-role-arn: arn:aws:iam::901562421220:role/node-CodeDeployRole
          bundle-bucket: node-circleci-s3          
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
          requires:
            - build-and-push
          filters:
              branches:
                only: master
        