version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: code-depoly-first-app
          deployment-group: code-depoly-first-app-depoly
          service-role-arn: arn:aws:iam::901562421220:role/node-backend-codedepoly 
          bundle-bucket: samplebucket-s3          
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
        