version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: node-code-deploy-app
          deployment-group: node-code-deploy-app-group
          service-role-arn: arn:aws:iam::901562421220:role/node-CodeDeployRole
          bundle-bucket: node-circleci-s3          
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
        